baseurl: "/"
languageCode: "en-us"
title: "Bruno Montezano"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About
      url: "about/"
      weight: 2
    - name: CV
      url: "cv/"
      weight: 3
    - name: Categories
      url: "categories/"
      weight: 4
    - name: Tags
      url: "tags/"
      weight: 5
    - name: Subscribe
      url: "index.xml"

params:
  description: "A website built through Hugo and blogdown."
  footer: "&copy; [Bruno Montezano](https://bmontezano.netlify.app) 2022 -- {Year} | [Github](https://github.com/brunomontezano) | [LinkedIn](https://www.linkedin.com/in/bmontezano)"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
